name: Auto Commits

on: pull_request

permissions:
  contents: write

jobs:
  commits:
    runs-on: ubuntu-latest

    steps:
      - uses: laboperator-gmbh/github-actions/yarn/dedupe@v1
      - name: Update build
        run: |
          yarn build

          if [[ `git status -s` ]]; then \
            git add .
            git commit -m '[dependabot skip] Update Build'
            git push
          fi
