name: License Checker

on:
  pull_request:
    branches-ignore:
      - "main"

jobs:
  license-check:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code to runner
        uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run yarn install
        run: yarn install

      - name: Check licenses
        run: |
          WHITELIST=$(cat ${{ github.workspace }}/license-whitelist.yml | paste -sd\; -)
          yarn license-checker-rseidelsohn --production --direct --excludePrivatePackage --onlyAllow "$WHITELIST" --summary 
          echo "âœ…  All licenses are compliant."
